### ISSUE TITLE
hbase go  create namespace  error. 

### ISSUE THREAD

**Issue by bigwalle** [aliyun/aliyun-apsaradb-hbase-demo#142]
�����)org.apache.hadoop.ipc.RPC$VersionMismatchCServer IPC version [6, 3] cannot communicate with client version 32���sz

![image](https://user-images.githubusercontent.com/11868709/203885972-5ed33568-6536-4d4b-bbea-68c3450b320b.png)

**Comment by bakea** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件我已经收到！

**Comment by bigwalle** [comment]
问题已经解决 ， 是非java 语言提供
